### ISSUE TITLE
Provide mechanism to use different header definitions, same payload definition

### ISSUE THREAD

**Issue by skliper** [nasa/cFS-GroundSystem#103]
**Is your feature request related to a problem? Please describe.**
Multiple header formats are not easily supported in current implementation of the GUI.

**Describe the solution you'd like**
Make it easier (for example cFS version 1 or version 2 selection should be easy).

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by lbleier-GSFC** [comment]
It would seem that doing this also involves #61. I can try to implement cmdUtil functionality in python
