### ISSUE TITLE
Resolve build warnings

### ISSUE THREAD

**Issue by skliper** [nasa/cFS-GroundSystem#12]
2 warnings from cc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609

/home/jhageman/cFS/cFS-dev/tools/cFS-GroundSystem/Subsystems/cmdUtil/cmdUtil.c: In function ‘ProcessStringArgument’:
/home/jhageman/cFS/cFS-dev/tools/cFS-GroundSystem/Subsystems/cmdUtil/cmdUtil.c:239:16: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long int’ [-Wformat=]
         printf("String Length is %d.\n", stringLength);
                ^

/home/jhageman/cFS/cFS-dev/tools/cFS-GroundSystem/Subsystems/cmdUtil/sendUdp.c: In function ‘SendUdp’:
/home/jhageman/cFS/cFS-dev/tools/cFS-GroundSystem/Subsystems/cmdUtil/sendUdp.c:74:12: warning: implicit declaration of function ‘atoi’ [-Wimplicit-function-declaration]
     port = atoi(portNum);
            ^

**Comment by mrosburg** [comment]
Okay, I try this issue.

**Comment by skliper** [comment]
Heads up on the first one, preference is to fix the format vs cast.

**Comment by jphickey** [comment]
On printf statements it is generally not possible to fix the format when the type is a fixed width int (i.e. uint32).  A cast is generally needed here. My recommendation is to use %ld conversion AND cast the argument to "long int" as well.

**Comment by skliper** [comment]
stringLength is not a fixed point int.  It's defined as long, just use %ld.

**Comment by jphickey** [comment]
Yes I concur then, if it is actually "long" then no cast.

**Comment by skliper** [comment]
Any updates on this issue?  Do you have an expected completion date?

**Comment by mrosburg** [comment]
Not sure if you'll get this but I have been delayed in doing this ticket
because of higher priority work.

Mike

**Comment by mrosburg** [comment]
You can reassign it.

**Comment by avan989** [comment]
I can do this.
