### ISSUE TITLE
Closing the ground system should close all of its windows

### ISSUE THREAD

**Issue by astrogeco** [nasa/cFS-GroundSystem#121]
**Describe the bug**
If other ground system windows are open, clicking "close" on the main GroundSystem window only stops the process and closes tha main window. All the other windows stay on the main screen

Using ctrl-c on the main terminal running the ground system also leaves the windows up

**To Reproduce**
(1) Open the ground system and a couple of windows, click "close" on the original GrounSystem menu. 

(2) Open the ground system and a couple of windows, use ctrl-c and stop the python process.

**Expected behavior**
All windows close when exiting the ground system

**Code snips**
None

**System observed on:**
Gnome VM 

**Additional context**
None

**Reporter Info**
Gerardo E. Cruz-Ortiz, NASA-GSFC

**Comment by zachar1a** [comment]
Using ctrl + c doesn't call the closeEvent function and I haven't been successful in creating a handler that does. But when used with `os.kill(0, signal.SIGKILL) ` the closeEvent can shutdown all of the subprocesses.
