### ISSUE TITLE
"start" script or at least make GroundSystem.py executable

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/cFS-GroundSystem#123]
**Is your feature request related to a problem? Please describe.**
Currently users have to explicitly type `python3 GroundSystem.py` to start the ground system. (And if they type `bash GroundSystem.py` or `python GroundSystem.py` [and the default Python is 2] they get errors.) At minimum the GroundSystem.py file should be made executable so users can use `./GroundSystem.py` and not worry about what is the correct scripting language. This will also likely help with GUI file managers, enabling starting from the GUI without having to go to a terminal.

It might be better to have a short `start` or `go` or even just rename it to `GroundSystem` (no extension) or some other obvious command that starts the ground system. Given the folder's full of .py files, having a file that's distinct will be helpful to new users. Would like CCB's consideration on what to name such a command.

**Requester Info**
Christopher.D.Knight@nasa.gov

**Comment by sunny1401** [comment]
Hi - I was wondering if I can try doing this?

**Comment by CDKnightNASA** [comment]
> Hi - I was wondering if I can try doing this? - Not sure if I can contribute to this?

Absolutely!

**Comment by sunny1401** [comment]
Thank you
