### ISSUE TITLE
Remove .DS_Store file

### ISSUE THREAD

**Issue by skliper** [nasa/cFS-GroundSystem#13]
MacOS leftover file that snuck into the repository.

**Comment by JarrettCFranklin** [comment]
I'll grab this one.

**Comment by skliper** [comment]
@JarrettCFranklin are you able to address this issue or should I reassign?

**Comment by JarrettCFranklin** [comment]
Got caught up with work stuff. I plan on resolving this weekend.

**Comment by JarrettCFranklin** [comment]
starting. Sorry for the delay.

**Comment by zacnyjegomosc** [comment]
Can I take over this issue?

**Comment by JarrettCFranklin** [comment]
Yes
