### ISSUE TITLE
GroundSystem.py run error

### ISSUE THREAD

**Issue by GitHubForPP** [nasa/cFS-GroundSystem#138]
**Describe the bug**
run python3 GroundSystem.py prompt
File "GroundSystem.py", line 102
    subscription += f'.{selectedSpacecraft}.TelemetryPackets'
                                                            ^
SyntaxError: invalid syntax

**To Reproduce**
1.sudo apt-get install python3-pyqt5
2.sudo apt-get install python3-zmq
3.sudo apt-get install libcanberra-gtk-module
4.cd Subsystems/cmdUtil/ && make
5.python3 GroundSystem.py

**Expected behavior**

**Code snips**
If applicable, add references to the software.

**System observed on:**
 - Hardware
 - OS: UBUNTU 16.04

**Additional context**

**Reporter Info**
Full name and company/organization if applicable

**Comment by skliper** [comment]
@GitHubForPP Did you get this to work?

**Comment by GitHubForPP** [comment]
> @GitHubForPP您使它起作用了吗？

Yes,you can use it by updating the python version to 3.7.
