### ISSUE TITLE
Replace non-ascii characters

### ISSUE THREAD

**Issue by skliper** [nasa/cFS-GroundSystem#14]
./Subsystems/Commands-Telemetry.txt:9:51: error: character code 226 (0xE2) is not portable.
./Subsystems/Commands-Telemetry.txt:66:49: error: character code 226 (0xE2) is not portable.
./Guide-GroundSystem.txt:13:241: error: character code 226 (0xE2) is not portable.
./Guide-GroundSystem.txt:21:3: error: character code 226 (0xE2) is not portable.
./Guide-GroundSystem.txt:22:3: error: character code 226 (0xE2) is not portable.
./Guide-GroundSystem.txt:23:3: error: character code 226 (0xE2) is not portable.

**Comment by declansullivan** [comment]
I would love to help out with this.
