### ISSUE TITLE
Update executable name and version in setup.py

### ISSUE THREAD

**Issue by astrogeco** [nasa/cFS-GroundSystem#172]
The info in setup.py needs to be edited. 

>Rename to "cFS-GroundSystem" and update version to use the number in version.py

_Originally posted by @astrogeco in https://github.com/nasa/cFS-GroundSystem/pull/137#discussion_r598736996_

**Comment by zachar1a** [comment]
The command to execute is 'startg' is that fine or should that also be renamed?

**Comment by astrogeco** [comment]
> The command to execute is 'startg' is that fine or should that also be renamed?

I'd probably rename that as well. Though I can't think of a good name. I'll discuss it with the team
