### ISSUE TITLE
Virutualenv and Pipenv support within .gitignore

### ISSUE THREAD

**Issue by pavll** [nasa/cFS-GroundSystem#189]
**Is your feature request related to a problem? Please describe.**
If you work with an IDE like PyCharm from Jetbrains you have to be careful when committing not to send the `.idea` folder by mistake because it is not listed in the `.gitignore`. Also missing is the exclusion of `venv` folders and `Pipenv` files in the `.gitignore`. I think some developers will be happy about this change.

**Describe the solution you'd like**
Structured .gitignore with the changes from above.

**Describe alternatives you've considered**
Do the excluding manually every time you have some of these in your code.

**Additional context**
I will add a PR that includes the above changes.

**Requester Info**
pavll

**Comment by astrogeco** [comment]
Hey @pavll did you close this by accident?

**Comment by pavll** [comment]
Yes
