### ISSUE TITLE
cmdUtil is not 64-bit friendly

### ISSUE THREAD

**Issue by skliper** [nasa/cFS-GroundSystem#2]
Originated from glimes (45 on babelfish)

As part of our "switch flip" to 64-bit on AOS, we needed to make changes to the cmdUtil program to make it 64-bit clean (the version we had, in at least one place, presumed that "long" was 32 bits).
When I refactored it to clean out the 32/64 dependency, I rerouted all the numeric data encoding through a common function, and ended up eliminating any need for the cmdUtil program to know its own endianness.

**Comment by avan989** [comment]
Can you clarify what needs to be done?

**Comment by skliper** [comment]
Real solution is EDS and not a critical short term fix
