### ISSUE TITLE
cmdUtil.h not being use

### ISSUE THREAD

**Issue by avan989** [nasa/cFS-GroundSystem#24]
cmdUtil.h is not being used. Only contain the prototypes for SendUdp. Suggest using it cmdUtil.h or deleting it.

**Comment by skliper** [comment]
Good call.  Requested updates - change the name to SendUdp.h, change sendUdp.c to SendUdp.c, include SendUdp.h in SendUdp.c and cmdUtil.c, remove local prototype of SendUdp in cmdUtil.c.
