### ISSUE TITLE
Invalid command length

### ISSUE THREAD

**Issue by avan989** [nasa/cFS-GroundSystem#29]
**Describe the bug**
There are discrepancies between the groundsystem command length and what cFS is expecting:

EventService:

1) Delete Application Event Filter command :
    Error: Invalid cmd length: ID = 0x1801, CC = 16, Exp Len = 30, Len = 32

Time Service:

1) Set Tone Signal Source command
     Error:  Invalid cmd length: ID = 0x1805, CC = 15, Exp Len = 10, Len = 8

Table Service:

1) Abort Table Load command:
    Error: Invalid msg length -- ID = 0x1804, CC = 9, Len = 24 (!= 46)
2) Activate Table command:Invalid msg length -- ID = 0x1804, CC = 5, Len = 24 (!= 46)
3) Delete Critical Table from Critical Data Store Command
    Error: Invalid msg length -- ID = 0x1804, CC = 8, Len = 24 (!= 46)
4) Dump Table command
    Error: Invalid msg length -- ID = 0x1804, CC = 3, Len = 90 (!= 112)
5) Telemeter One Table Registry Entry command
     Error: Invalid msg length -- ID = 0x1804, CC = 7, Len = 24 (!= 46)
6) Validate Table command: 
    Error: Invalid msg length -- ID = 0x1804, CC = 4, Len = 26 (!= 48)

Software Bus:

1) Disable Software Bus Route command:
    Error: Invalid cmd length: ID = 0x1803, CC = 5, Exp Len = 12, Len = 9
2) Enable Software Bus Route command:
    Error: Invalid cmd length: ID = 0x1803, CC = 4, Exp Len = 12, Len = 9

Executive Service:

1) Delete Critical Data Store command:
    Error: Invalid cmd length: ID = 0x1806, CC = 21, Exp Len = 46, Len = 24

*To Reproduce**
1. Go to Ground System
2. Start cFS
3. In Ground System, click on the commands mention above
4. See errors in cFS

**System observed on:**
 - Hardware
 - OS: Ubuntu 18.04.03
 - CFE 6.6

**Reporter Info**
Anh Van, NASA Goddard

**Comment by skliper** [comment]
See https://github.com/nasa/cFE/blob/6aaf5a3244e02af43c8ebb893ef413916dff5ef2/fsw/cfe-core/src/inc/cfe_time_msg.h#L796-L811

For set signal command (CC=15)
