### ISSUE TITLE
Not all Time command implemented

### ISSUE THREAD

**Issue by avan989** [nasa/cFS-GroundSystem#31]
**Describe the bug**
Not all time commands in Ground System are implemented. 

**To Reproduce**
1. Go to Ground System
2. Check command definition vs. cFE definition 

**System observed on:**
 - Hardware
 - OS: 18.04.03
 - cFE 6.6, GroundSystem 2.0.90

**Reporter Info**
Anh Van, NASA Goddard

**Comment by dmknutsen** [comment]
I rebuilt all of the time commands as part of Fix #59.  This issue can be closed once pull request #60 is delivered.
