### ISSUE TITLE
Adding Python 3 compatibility

### ISSUE THREAD

**Issue by mlouielu** [nasa/cFS-GroundSystem#35]
**Is your feature request related to a problem? Please describe.**
In Python 3 default environment, using cFS-GroundSystem is a little tricky, since `GroundSystem.py` will use `/usr/bin/env python` for the `Subsystem`.

And the PyQt4 needs compile & build, it is hard to deploy in the virtual environment for it.

**Describe the solution you'd like**
Adding Python 3 compatibility for cFS-GroundSystem code.

**Describe alternatives you've considered**
By using `2to3`, we can convert most of the code.

Only 2 parts need to concern:

* csv reader open file
  * Adding a middle layer of open, or detect version in each files
* zmq.socket.setsockopt
  * Does the subscription name need to support utf-8?

**Additional context**
No

**Requester Info**
Louie Lu / Advanced Rocket Research Center, NCTU, Taiwan

**Comment by skliper** [comment]
Good issue, we do plan to update but as of today I can't except external contributions yet (still trying to get the process in place).  Hopefully soon!

@dmknutsen

**Comment by mlouielu** [comment]
Reading csv file should use `open(filename, 'r', newline='')` in Python 3.

Otherwise it will raise up:
```
>>> with open('cs-hk-tlm.txt', 'rb') as f:
...  reader = csv.reader(f)
...  for r in reader:
...   print(r)
... 
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)
```

This didn't address in de8c151.
