### ISSUE TITLE
lgtm c issues

### ISSUE THREAD

**Issue by avan989** [nasa/cFS-GroundSystem#43]
**Describe the bug**
Issues report from LGTM. 

SendUdp.h
```This header file should contain a header guard to prevent multiple inclusion.```

cmdUtil.c:

```
 line - 213, 254, 274, 293, 318, 339
void ProcessStringArgument(char *optarg, CommandData_t *CommandData) {
--
  | Parameter CommandData hides a global variable with the same name.

```

cmdUtil.c
```
line 62 -84
Struct struct <unnamed> has 16 fields; we suggest refactoring to 15 fields or fewer.

```

**To Reproduce**
1. Build against Lgtm

**Reporter Info**
Anh Van, NASA Goddard

**Comment by lbleier-GSFC** [comment]
This issue has been updated to be C-related only; Python issues have been consolidated into issue #46
