### ISSUE TITLE
Recommended lgtm python issues

### ISSUE THREAD

**Issue by avan989** [nasa/cFS-GroundSystem#46]
**Is your feature request related to a problem? Please describe.**
Recommendation from lgtm:

CHeaderParser.py

```
else:
--
325 | line_num += 1
326 | pass
  | Unnecessary 'pass' statement.
```

TlmMQRecv.py

```
# We never get here but clean up anyhow
--
42 | subscriber.close()
  | Unreachable statement.
43 |  
```

```
RoutingService.py

self.sock.bind(('', udpRecvPort))
--
  | '' binds a socket to all interfaces.

```

CommandParser.py
```
line 20:

import sys
--
  | Import of 'sys' is not used.
21 | import csv
  | Import of 'csv' is not used.
22 | import getopt
  | Import of 'getopt' is not used.
23 | import subprocess
  | Import of 'subprocess' is not used.
24 | import shlex
  | Import of 'shlex' is not used.
```

HTMLDocsParser.py
```
line 20:

import sys
--
  | Import of 'sys' is not used.
21 | import csv
  | Import of 'csv' is not used.
22 | import getopt
  | Import of 'getopt' is not used.
23 | import subprocess
  | Import of 'subprocess' is not used.
24 | import shlex
  | Import of 'shlex' is not used.


```
ParameterDialog.py
```
line 234:
def retranslateUi(self, Dialog):
--
  | All statements in retranslateUi are similar in 4 Values.

```

GroundSystem.py
```
line 26:
import socket
--
  | Import of 'socket' is not used.
27 | import zmq
  | Import of 'zmq' is not used.
28 |  
29 | from PyQt4 import QtGui, QtNetwork, QtCore
  | Import of 'QtCore' is not used.Import of 'QtNetwork' is not used.


# Start FDL-FUL gui system
98 | #def startFDLSystem(self):
99 | #    selectedSpacecraft = self.getSelectedSpacecraftName()
100 | #    if selectedSpacecraft == 'All':
101 | #        subscription = ''
102 | #        self.DisplayErrorMessage('Cannot open FDL manager.\nNo spacecraft selected.')
103 | #    else:
104 | #       subscription = '--sub=GroundSystem.' + selectedSpacecraft
105 | #       os.system('( cd Subsystems/fdlGui/ && python FdlSystem.py ' + subscription + ' ) & ')
  | These comments appear to contain commented-out code.
106 |  
```

RoutingService.py
```
line 23:
import sys
--
  | Import of 'sys' is not used.
24 | import os
  | Import of 'os' is not used.
25 | import socket
26 | import zmq
27 |  
28 | from PyQt4 import QtGui, QtNetwork, QtCore
  | Import of 'QtGui' is not used.Import of 'QtNetwork' is not used.
```

Paramete.py
```
import csv
--
  | Import of 'csv' is not used.


from PyQt4 import QtGui, QtNetwork
--
  | Import of 'QtNetwork' is not used.
29 | from ParameterDialog import Ui_Dialog
30 | from HTMLParser import HTMLParser
  | Import of 'HTMLParser' is not used.


line 104:
idx = 0
--
  | The global variable 'idx' is not used.


line 111:
params = ''
--
  | The global variable 'params' is not used.

line 125:
idx = int(arg) # comand index in command definition file
--
  | The global variable 'idx' is not used.

line 163, 169, 174, 179, 184, 189, 194, 199, 204, 209
'except' clause does nothing but pass and there is no explanatory comment.
```

UdpCommands.py
```
import csv
--
  | Import of 'csv' is not used.

from HTMLParser import HTMLParser
--
  | Import of 'HTMLParser' is not used.
```

CHeaderParser.py
```
import sys, os
--
  | Import of 'os' is not used.

line 437:
typeNew = parser.findKeyword(dataTypesOrig[-1])
--
  | The global variable 'typeNew' is not used.


except IOError as e:
--
115 | print "Couldn't find default file. Checking command line arguments."
116 | except:
  | Except block directly handles BaseException.


array_size_within_limit = True
--
489 | # End of the loop.
490 | except:
  | Except block directly handles BaseException.


#else:
--
188 | #       print "Did not find any comments in definition."
  | These comments appear to contain commented-out code.


```

GenericTelemetry.py
```
import pdb
--
  | Import of 'pdb' is not used.


class TlmReceiver(QtCore.QThread):
--
127 |  
128 | def __init__(self, mainWindow, subscription):
  | All 6 statements in __init__ are identical in __init__.


```

TlmUDPSender.py
```
import sys
--
  | Import of 'sys' is not used.
```

EventMessage.py
```
line 151 - 153
udpPort  = 10000
--
  | The global variable 'udpPort' is not used.
152 | appId = 999
153 | tlmDefFile = "not-needed.txt"
  | The global variable 'tlmDefFile' is not used.

line 171:
udpPort = arg
--
  | The global variable 'udpPort' is not used.

line 175:
tlmDefFile = arg
--
  | The global variable 'tlmDefFile' is not used.


line 193 - 195:
py_endian = '<'
--
  | The global variable 'py_endian' is not used.

py_endian = '>'
--
  | The global variable 'py_endian' is not used.
```

GenericTelemetry.py
```
line 166:
udpPort  = 10000
--
  | The global variable 'udpPort' is not used.

line 186:
udpPort = arg
--
  | The global variable 'udpPort' is not used.

line 252:
for j in range (i, 40):
--
  | The global variable 'j' is not used.
```

UdpCommands.py
```
line 247:
for i in range(len(cmdDesc)):
--
  | The global variable 'i' is not used.

line 249:
for i in range (len(cmdDesc), 26):
--
  | The global variable 'i' is not used.
```

CommandSystem.py
```
for j in range (i, 22):
--
  | The global variable 'j' is not used.

line 341, 355, 369, 383, 397, 411, 425, 439, 453, 467, 481, 495, 509, 523, 537, 551, 565, 579, 593, 607, 621, 635

'except' clause does nothing but pass and there is no explanatory comment.
```

TelemetrySystem.py
```

#
--
71 | def strToHex(aString):
  | Normal methods should have 'self', rather than 'aString', as their first parameter.


#
--
80 | def dumpPacket(packetData):
  | Normal methods should have 'self', rather than 'packetData', as their first parameter.



line 82:
appIdString = appIdString + "%02X" % ord(packetData[1])
--
  | The value assigned to local variable 'appIdString' is never used.

line 167:
def dumpPacket(packetData):
--
  | The value assigned to local variable 'dumpPacket' is never used.

line 192:
send_host = "127.0.0.1"
--
  | The value assigned to local variable 'send_host' is never used.

193 | send_port =  tlmPagePort[i]
  | The value assigned to local variable 'send_port' is never used.


line 249:
def __init__(self, mainWindow, subscription):
--
  | All 6 statements in __init__ are identical in __init__.
```

**Requester Info**
Anh Van, NASA Goddard

**Comment by lbleier-GSFC** [comment]
This issue has been updated to be Python-related only; C issues are consolidated in issue #43

**Comment by skliper** [comment]
@lbleier-GSFC have these been resolved as part of your previous work?  Doesn't look like these are listing the autogenerated files,

**Comment by skliper** [comment]
@lbleier-GSFC see https://lgtm.com/projects/g/nasa/cFS/alerts/?mode=list&lang=python for the latest set of issues.  These all look to be against hand generated files.  Can they be resolved?

**Comment by lbleier-GSFC** [comment]
> @lbleier-GSFC see https://lgtm.com/projects/g/nasa/cFS/alerts/?mode=list&lang=python for the latest set of issues. These all look to be against hand generated files. Can they be resolved?

I'm very confused. I fixed these already. I am looking at my local copies and they are fixed. Not only that, the auto-generated ones should be deleted because I changed the filenames (added the `Ui_` prefix)

**Comment by skliper** [comment]
> > @lbleier-GSFC see https://lgtm.com/projects/g/nasa/cFS/alerts/?mode=list&lang=python for the latest set of issues. These all look to be against hand generated files. Can they be resolved?
> 
> I'm very confused. I fixed these already. I am looking at my local copies and they are fixed. Not only that, the auto-generated ones here should be deleted because I changed the filenames (added the `Ui_` prefix)

Did you?  I just looked in master for the first LGTM alert, and it was still in the code (QtGui not used in CommandSystemDialog.py).  Did you submit something that didn't get checked in?  What are you looking at locally?  Is there a branch you have locally that needs a PR?

**Comment by lbleier-GSFC** [comment]
> > > @lbleier-GSFC see https://lgtm.com/projects/g/nasa/cFS/alerts/?mode=list&lang=python for the latest set of issues. These all look to be against hand generated files. Can they be resolved?
> > 
> > 
> > I'm very confused. I fixed these already. I am looking at my local copies and they are fixed. Not only that, the auto-generated ones here should be deleted because I changed the filenames (added the `Ui_` prefix)
> 
> Did you? I just looked in master for the first LGTM alert, and it was still in the code (QtGui not used in CommandSystemDialog.py). Did you submit something that didn't get checked in? What are you looking at locally? Is there a branch you have locally that needs a PR?

That particular file is auto-generated. I fixed the alerts for files that were hand-written

**Comment by skliper** [comment]
> > > > @lbleier-GSFC see https://lgtm.com/projects/g/nasa/cFS/alerts/?mode=list&lang=python for the latest set of issues. These all look to be against hand generated files. Can they be resolved?
> > > 
> > > 
> > > I'm very confused. I fixed these already. I am looking at my local copies and they are fixed. Not only that, the auto-generated ones here should be deleted because I changed the filenames (added the `Ui_` prefix)
> > 
> > 
> > Did you? I just looked in master for the first LGTM alert, and it was still in the code (QtGui not used in CommandSystemDialog.py). Did you submit something that didn't get checked in? What are you looking at locally? Is there a branch you have locally that needs a PR?
> 
> That particular file is auto-generated. I fixed the alerts for files that were hand-written.
> 
> I am looking at the branch I made for this issue

Copy.  Looks like LGTM hasn't run an updated analysis on the latest master yet.  I haven't been able to trigger it, but apparently it does a daily pull.

**Comment by lbleier-GSFC** [comment]
> > > > > @lbleier-GSFC see https://lgtm.com/projects/g/nasa/cFS/alerts/?mode=list&lang=python for the latest set of issues. These all look to be against hand generated files. Can they be resolved?
> > > > 
> > > > 
> > > > I'm very confused. I fixed these already. I am looking at my local copies and they are fixed. Not only that, the auto-generated ones here should be deleted because I changed the filenames (added the `Ui_` prefix)
> > > 
> > > 
> > > Did you? I just looked in master for the first LGTM alert, and it was still in the code (QtGui not used in CommandSystemDialog.py). Did you submit something that didn't get checked in? What are you looking at locally? Is there a branch you have locally that needs a PR?
> > 
> > 
> > That particular file is auto-generated. I fixed the alerts for files that were hand-written.
> > I am looking at the branch I made for this issue
> 
> Copy. Looks like LGTM hasn't run an updated analysis on the latest master yet. I haven't been able to trigger it, but apparently it does a daily pull.

What's odd is that I renamed auto-generated files such as these to have the `Ui_` prefix in their filename. The pre-renamed files should be deleted as far as git is concerned. I am not sure why they are still coming up

**Comment by skliper** [comment]
@lbleier-GSFC coming up where?  In LGTM it is because the last run was on a previous commit.  You can see the commit it used and compare it with master (it's using the 6/10 IC merge last I checked).
