### ISSUE TITLE
Update build/run instructions for python 3

### ISSUE THREAD

**Issue by skliper** [nasa/cFS-GroundSystem#50]
**Is your feature request related to a problem? Please describe.**
Guide-GroundSystem.txt is now out of date based on python 3 updates.

**Describe the solution you'd like**
Update the install/run guide

**Describe alternatives you've considered**
Move to a wiki, document in README, etc.

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by mprather** [comment]
As a request for future releases that involve a rather large dependency change - please release the updated instructions simultaneously. I spent the better part of an afternoon trying to understand why my system could not get the simple readme instructions to work properly. Documentation is key for new users. I read through GroundSystem.txt at least a half dozen times and restarted my install at least 3 times. I was off in the weeds thinking my os installs were busted. It finally dawned on me that my first working install from mid-January probably had a different dependency than today's install. Sure enough, digging through the commits of the past 2 weeks, I found that the scripts had changed over to python3. Then the errors began to make sense ... 

Thanks!
