### ISSUE TITLE
Scrub/Redo GroundSystem command

### ISSUE THREAD

**Issue by avan989** [nasa/cFS-GroundSystem#57]
**Is your feature request related to a problem? Please describe.**
Some of the commands are outdated and does not match current cFS. 

**Describe the solution you'd like**
Redo all command to ensure everything is updated. 

**Describe alternatives you've considered**
Scrubbing and fixing the parameter files manually (more difficult than just redoing the command)

**Additional context**
Add-on to issue #31

**Requester Info**
Anh Van, NASA Goddard

**Comment by skliper** [comment]
@dmknutsen I think you are also working this?

**Comment by dmknutsen** [comment]
I am.  I submitted a similar ticket + rebuilt all of the commands and submitted a pull request yesterday to fix this (under issue #59).

**Comment by skliper** [comment]
Marking as duplicate of #59 and closing
