### ISSUE TITLE
Make scripts executable

### ISSUE THREAD

**Issue by skliper** [nasa/cFS-GroundSystem#7]
Originated by abrown4 (47 on babelfish) as a general ticket

**Comment by skliper** [comment]
See https://stackoverflow.com/questions/40978921/how-to-add-chmod-permissions-to-file-in-git

**Comment by avan989** [comment]
Can you clarify? Do you want to make all the python scripts executable or the shell script? Or referring to any scripting files?

**Comment by avan989** [comment]
I did a diff upstream. These showed up as changes so I pushed the changes up.
