### ISSUE TITLE
Sequence count likely not coming from header

### ISSUE THREAD

**Issue by skliper** [nasa/cFS-GroundSystem#71]
**Describe the bug**
Looks like sequence count as displayed on the telemetry subsystem pages is not the sequence count from the header

**To Reproduce**
1. Start cFE, start cFS-GroundStation, open cmd and tlm pages
1. Send enable tlm command to 127.0.0.1
1. Wait for packet counter to increment (> 1)
1. Open ES subsystem page, sequence count will start at 1 and increment (should start higher since packets have been received)
1. Close ES subsystem page, reopen and sequence count will start at 1 again

**Expected behavior**
Sequence count should be coming from the packet header, wouldn't restart every time the page opens.

**Code snips**
Haven't investigated yet

**System observed on:**
 - Hardware; cFS Dev Server 3
 - OS: Ubuntu 18.04
 - Versions: Current bundle

**Additional context**
Found during #66 testing

**Reporter Info**
Jacob Hageman - NASA/GSFC

**Comment by lbleier-GSFC** [comment]
I have discovered the source of this issue, but it might take me a bit to come with a good solution.
