### ISSUE TITLE
Convert the guide to markdown

### ISSUE THREAD

**Issue by skliper** [nasa/cFS-GroundSystem#9]
Guide-GroundSystem.txt should be markdown and needs a scrub.

**Comment by skliper** [comment]
Note install instruction update addressed in #50.

**Comment by zacnyjegomosc** [comment]
@skliper Can I grab this issue?

**Comment by skliper** [comment]
Assigned, thanks!  Note as referenced on the pull request template (the contributor doc is still in work) we will need one of the CLA forms.  See https://github.com/nasa/cFE/blob/master/docs/GSC_18128_Corp_CLA_form_1219.pdf for work done as part of a job or https://github.com/nasa/cFE/blob/master/docs/GSC_18128_Ind_CLA_form_1219.pdf for individual contribution.

Submission instructions are on the form (email preferred).
