### ISSUE TITLE
Refactor individual fields to table

### ISSUE THREAD

**Issue by lbleier-GSFC** [nasa/cFS-GroundSystem#98]
**Is your feature request related to a problem? Please describe.**
The individual fields in the generic telemetry and command windows use dozens of individual UI elements.

**Describe the solution you'd like**
Replace fields with table widget

**Additional context**
A single table widget would make UI easier to use and maintain

**Requester Info**
Leor Bleier, NASA GSFC\Code 582

**Comment by skliper** [comment]
@lbleier-GSFC please explicitly link this to your pull request.
