### ISSUE TITLE
Fix Markdown for Ground System Guide

### ISSUE THREAD

**Issue by astrogeco** [nasa/cFS-GroundSystem#99]
**Is your feature request related to a problem? Please describe.**
Multiple numbering and formatting inconsistencies in Guide-GroundSystem.md.
Duplicate file with Guide-GroundSystem.txt

**Describe the solution you'd like**
Remove Guide-GroundSystem.txt and update Markdown file using [remark](https://github.com/remarkjs/remark), [prettier](https://prettier.io/) or [Tidy Markdown](https://github.com/notslang/tidy-markdown)

Long-term create a implement style guide for Markdown

Rename file to follow CamelCase.

**Describe alternatives you've considered**
Short manual scrub to fix numbering and code blocks.

**Comment by zacnyjegomosc** [comment]
Absolutely. Can I grab this issue?

**Comment by astrogeco** [comment]
> Absolutely. Can I grab this issue?

Take it away!

The markdown formatting examples are just meant as guidelines. You might want to look into the different toolchains and do a pros/cons between them. I envision something similar to what we did with clang-format. See the cFS repo's .travis file

**Comment by skliper** [comment]
Looks to me like just an end of code quote got messed up...

**Comment by astrogeco** [comment]
There's some weird numbering stuff happening in the steps section too.
